obj-m += hostapd_driver.o
hostapd_driver-objs := 	hostapd-2.11/hostapd/main.o \
	hostapd-2.11/hostapd/config_file.o \
	hostapd-2.11/hostapd/../src/ap/hostapd.o \
	hostapd-2.11/hostapd/../src/ap/wpa_auth_glue.o \
	hostapd-2.11/hostapd/../src/ap/drv_callbacks.o \
	hostapd-2.11/hostapd/../src/ap/ap_drv_ops.o \
	hostapd-2.11/hostapd/../src/ap/utils.o \
	hostapd-2.11/hostapd/../src/ap/authsrv.o \
	hostapd-2.11/hostapd/../src/ap/ieee802_1x.o \
	hostapd-2.11/hostapd/../src/ap/ap_config.o \
	hostapd-2.11/hostapd/../src/ap/eap_user_db.o \
	hostapd-2.11/hostapd/../src/ap/ieee802_11_auth.o \
	hostapd-2.11/hostapd/../src/ap/sta_info.o \
	hostapd-2.11/hostapd/../src/ap/wpa_auth.o \
	hostapd-2.11/hostapd/../src/ap/tkip_countermeasures.o \
	hostapd-2.11/hostapd/../src/ap/ap_mlme.o \
	hostapd-2.11/hostapd/../src/ap/wpa_auth_ie.o \
	hostapd-2.11/hostapd/../src/ap/preauth_auth.o \
	hostapd-2.11/hostapd/../src/ap/pmksa_cache_auth.o \
	hostapd-2.11/hostapd/../src/ap/ieee802_11_shared.o \
	hostapd-2.11/hostapd/../src/ap/beacon.o \
	hostapd-2.11/hostapd/../src/ap/bss_load.o \
	hostapd-2.11/hostapd/../src/ap/neighbor_db.o \
	hostapd-2.11/hostapd/../src/ap/rrm.o \
	hostapd-2.11/hostapd/../src/common/ptksa_cache.o \
	hostapd-2.11/hostapd/../src/drivers/drivers.o \
	hostapd-2.11/hostapd/../src/utils/eloop.o \
	hostapd-2.11/hostapd/../src/utils/common.o \
	hostapd-2.11/hostapd/../src/utils/wpa_debug.o \
	hostapd-2.11/hostapd/../src/utils/wpabuf.o \
	hostapd-2.11/hostapd/../src/utils/os_unix.o \
	hostapd-2.11/hostapd/../src/utils/ip_addr.o \
	hostapd-2.11/hostapd/../src/utils/crc32.o \
	hostapd-2.11/hostapd/../src/common/ieee802_11_common.o \
	hostapd-2.11/hostapd/../src/common/wpa_common.o \
	hostapd-2.11/hostapd/../src/common/hw_features_common.o \
	hostapd-2.11/hostapd/../src/eapol_auth/eapol_auth_sm.o \
	hostapd-2.11/hostapd/../src/eapol_auth/eapol_auth_dump.o \
	hostapd-2.11/hostapd/../src/radius/radius.o \
	hostapd-2.11/hostapd/../src/radius/radius_client.o \
	hostapd-2.11/hostapd/../src/radius/radius_das.o \
	hostapd-2.11/hostapd/../src/ap/accounting.o \
	hostapd-2.11/hostapd/../src/ap/vlan_init.o \
	hostapd-2.11/hostapd/../src/ap/vlan_ifconfig.o \
	hostapd-2.11/hostapd/../src/ap/vlan.o \
	hostapd-2.11/hostapd/../src/common/ctrl_iface_common.c \
	hostapd-2.11/hostapd/ctrl_iface.o \
	hostapd-2.11/hostapd/../src/ap/ctrl_iface_ap.o \
	hostapd-2.11/hostapd/../src/drivers/driver_hostap.o \
	hostapd-2.11/hostapd/../src/drivers/driver_nl80211.o \
	hostapd-2.11/hostapd/../src/drivers/driver_nl80211_capa.o \
	hostapd-2.11/hostapd/../src/drivers/driver_nl80211_event.o \
	hostapd-2.11/hostapd/../src/drivers/driver_nl80211_monitor.o \
	hostapd-2.11/hostapd/../src/drivers/driver_nl80211_scan.o \
	hostapd-2.11/hostapd/../src/drivers/netlink.o \
	hostapd-2.11/hostapd/../src/drivers/rfkill.o \
	hostapd-2.11/hostapd/../src/utils/radiotap.o \
	hostapd-2.11/hostapd/../src/drivers/linux_ioctl.o \
	hostapd-2.11/hostapd/../src/l2_packet/l2_packet_linux.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_md5.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_tls.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_peap.o \
	hostapd-2.11/hostapd/../src/eap_common/eap_peap_common.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_ttls.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_mschapv2.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_gtc.o \
	hostapd-2.11/hostapd/../src/common/dpp.o \
	hostapd-2.11/hostapd/../src/common/dpp_auth.o \
	hostapd-2.11/hostapd/../src/common/dpp_backup.o \
	hostapd-2.11/hostapd/../src/common/dpp_crypto.o \
	hostapd-2.11/hostapd/../src/common/dpp_pkex.o \
	hostapd-2.11/hostapd/../src/common/dpp_reconfig.o \
	hostapd-2.11/hostapd/../src/common/dpp_tcp.o \
	hostapd-2.11/hostapd/../src/ap/dpp_hostapd.o \
	hostapd-2.11/hostapd/../src/ap/gas_query_ap.o \
	hostapd-2.11/hostapd/eap_register.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server.o \
	hostapd-2.11/hostapd/../src/eap_common/eap_common.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_methods.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_identity.o \
	hostapd-2.11/hostapd/../src/crypto/ms_funcs.o \
	hostapd-2.11/hostapd/../src/eap_common/chap.o \
	hostapd-2.11/hostapd/../src/eap_server/eap_server_tls_common.o \
	hostapd-2.11/hostapd/../src/crypto/tls_openssl.o \
	hostapd-2.11/hostapd/../src/crypto/tls_openssl_ocsp.o \
	hostapd-2.11/hostapd/../src/crypto/crypto_openssl.o \
	hostapd-2.11/hostapd/../src/crypto/aes-siv.o \
	hostapd-2.11/hostapd/../src/crypto/aes-ctr.o \
	hostapd-2.11/hostapd/../src/crypto/sha1-prf.o \
	hostapd-2.11/hostapd/../src/crypto/sha1-tlsprf.o \
	hostapd-2.11/hostapd/../src/crypto/sha256-prf.o \
	hostapd-2.11/hostapd/../src/crypto/sha256-tlsprf.o \
	hostapd-2.11/hostapd/../src/crypto/sha256-kdf.o \
	hostapd-2.11/hostapd/../src/crypto/sha384-kdf.o \
	hostapd-2.11/hostapd/../src/crypto/sha512-kdf.o \
	hostapd-2.11/hostapd/../src/crypto/sha384-prf.o \
	hostapd-2.11/hostapd/../src/crypto/sha512-prf.o \
	hostapd-2.11/hostapd/../src/tls/asn1.o \
	hostapd-2.11/hostapd/../src/crypto/random.o \
	hostapd-2.11/hostapd/../src/utils/base64.o \
	hostapd-2.11/hostapd/../src/utils/json.o \
	hostapd-2.11/hostapd/../src/ap/wmm.o \
	hostapd-2.11/hostapd/../src/ap/ap_list.o \
	hostapd-2.11/hostapd/../src/ap/comeback_token.o \
	hostapd-2.11/hostapd/../src/pasn/pasn_responder.o \
	hostapd-2.11/hostapd/../src/pasn/pasn_common.o \
	hostapd-2.11/hostapd/../src/ap/ieee802_11.o \
	hostapd-2.11/hostapd/../src/ap/hw_features.o \
	hostapd-2.11/hostapd/../src/ap/dfs.o \
	hostapd-2.11/hostapd/../src/ap/ieee802_11_ht.o \
	hostapd-2.11/hostapd/../src/common/gas.o \
	hostapd-2.11/hostapd/../src/ap/gas_serv.o \
	hostapd-2.11/hostapd/../src/drivers/driver_common.o \
	hostapd-2.11/hostapd/hostapd_cli.o \
	hostapd-2.11/hostapd/../src/common/wpa_ctrl.o \
	hostapd-2.11/hostapd/../src/common/cli.o \
	hostapd-2.11/hostapd/../src/utils/edit_simple.o


ccflags-y += -I./hostapd-2.11/hostapd 
ccflags-y += -I./hostapd-2.11/src/ap 
ccflags-y += -I./hostapd-2.11/src/common 
ccflags-y += -I./hostapd-2.11/src/crypto 
ccflags-y += -I./hostapd-2.11/src/drivers 
ccflags-y += -I./hostapd-2.11/src/eap_common 
ccflags-y += -I./hostapd-2.11/src/eapol_auth 
ccflags-y += -I./hostapd-2.11/src/eapol_supp 
ccflags-y += -I./hostapd-2.11/src/eap_peer 
ccflags-y += -I./hostapd-2.11/src/eap_server 
ccflags-y += -I./hostapd-2.11/src/fst 
ccflags-y += -I./hostapd-2.11/src/l2_packet 
ccflags-y += -I./hostapd-2.11/src/p2p 
ccflags-y += -I./hostapd-2.11/src/pae 
ccflags-y += -I./hostapd-2.11/src/pasn 
ccflags-y += -I./hostapd-2.11/src/radius 
ccflags-y += -I./hostapd-2.11/src/rsn_supp 
ccflags-y += -I./hostapd-2.11/src/tls 
ccflags-y += -I./hostapd-2.11/src/utils 
ccflags-y += -I./hostapd-2.11/src/wps
ccflags-y += -I./hostapd-2.11/src


ccflags-y += -I./porting
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

